-- 中介资质审核表
CREATE TABLE IF NOT EXISTS `biz_agent_qualification` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `agent_id` BIGINT(20) NOT NULL COMMENT '中介用户ID',
  `company_name` VARCHAR(255) NOT NULL COMMENT '中介公司名称',
  `business_license` VARCHAR(255) NOT NULL COMMENT '营业执照号',
  `license_image` VARCHAR(500) NOT NULL COMMENT '营业执照图片URL',
  `qualification_cert` VARCHAR(255) NOT NULL COMMENT '中介资质证书号',
  `cert_image` VARCHAR(500) NOT NULL COMMENT '资质证书图片URL',
  `contact_name` VARCHAR(100) NOT NULL COMMENT '联系人姓名',
  `contact_phone` VARCHAR(20) NOT NULL COMMENT '联系人电话',
  `audit_status` INT(11) DEFAULT 0 COMMENT '审核状态（0-待审核，1-审核通过，2-审核拒绝）',
  `audit_remark` TEXT COMMENT '审核意见',
  `auditor_id` BIGINT(20) COMMENT '审核人ID',
  `audit_time` DATETIME COMMENT '审核时间',
  `created_by` BIGINT(20) COMMENT '创建人',
  `created_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_by` BIGINT(20) COMMENT '更新人',
  `updated_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` TINYINT(4) DEFAULT 0 COMMENT '逻辑删除标识',
  PRIMARY KEY (`id`),
  KEY `idx_agent_id` (`agent_id`),
  KEY `idx_audit_status` (`audit_status`),
  CONSTRAINT `fk_agent_qualification_user` FOREIGN KEY (`agent_id`) REFERENCES `sys_user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='中介资质审核表';